notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
    - os: osx
      language: generic
      before_cache:
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
      env: PYTHON=3.8.3
      before_install:
        - brew update
        - brew install openssl readline
        - brew outdated pyenv || brew upgrade pyenv
        - brew install pyenv-virtualenv
        - sudo pyenv install $PYTHON
        - export PYENV_VERSION=$PYTHON
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - sudo pyenv virtualenv venv
        - ls venv
        - ls venv/bin
        - source venv/bin/activate
        - sudo python --version
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      install:
        - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
        - tar xvfz libsodium-1.0.18.tar.gz
        - cd libsodium-1.0.18
        - sudo ./configure
        - sudo make
        - sudo make install
        - cd ..
        - sudo python -m pip install -U pip
        - sudo python -m easy_install -U setuptools
        - sudo python -m pip install setuptools
        - sudo python -m pip install nose
        - sudo python -m pip install fe25519
        - sudo python -m pip install ge25519
        - sudo python -m pip install parts
        - sudo python -m pip install bitlist
        - sudo python -m pip install fountains
script:
  - nosetests
