notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
    - os: osx
      language: generic
      before_install:
        - wget https://github.com/actions/python-versions/releases/download/3.8.3-20200603.38/python-3.8.3-darwin-x64.tar.gz
        - sudo tar xjf python-3.8.3-darwin.tar.bz2 --directory /
        - sudo cp /usr/local/Cellar/python@3.8/3.8.3/bin/python3.8 /usr/local/bin/python
      install:
        - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
        - tar xvfz libsodium-1.0.18.tar.gz
        - cd libsodium-1.0.18
        - sudo ./configure
        - sudo make
        - sudo make install
        - cd ..
        - sudo python -m pip install setuptools
        - sudo python -m pip install nose
        - sudo python -m pip install fe25519
        - sudo python -m pip install ge25519
        - sudo python -m pip install parts
        - sudo python -m pip install bitlist
        - sudo python -m pip install fountains
script:
  - nosetests
