notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
  - "3.7"
  - "3.8"
cache: pip
install:
  - wget https://github.com/jedisct1/libsodium/archive/1.0.18.tar.gz
  - tar xvfz libsodium-1.0.18.tar.gz
  - cd libsodium-1.0.18
  - ./configure --prefix=$HOME/libsodium
  - make
  - make install
  - pip install pylint
  - pip install coveralls
  - pip install .
script:
  - pylint oblivious
  - nosetests
after_success:
  - coveralls
