notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - wget https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18-msvc.zip
        - unzip libsodium-1.0.18-msvc.zip
        - cp libsodium/Win32/Release/v142/dynamic/libsodium.dll /c/Windows/system32
        - choco install python --version=3.8.3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install pylint
        - pip install nose
        - pip install coveralls
        - pip install .
script:
  - pylint oblivious
  - nosetests
