notifications:
  email:
    on_success: never
    on_failure: never
language: python
python:
  - "3.8"
cache: pip
install:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
  - tar xvfz libsodium-1.0.18.tar.gz
  - cd libsodium-1.0.18
  - sudo ./configure
  - sudo make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - pip install .
script:
  - nosetests
