notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
    - os: osx
      language: generic
      install:
        - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
        - tar xvfz libsodium-1.0.18.tar.gz
        - cd libsodium-1.0.18
        - sudo ./configure
        - sudo make
        - sudo make install
        - cd ..
        - pip install .
script:
  - nosetests
