notifications:
  email:
    on_success: never
    on_failure: never
language: python
python:
  - "3.8"
cache: pip
before_install:	
  - sudo apt-get -y install libsodium-dev
install:
  - pip install pylint
  - pip install .
script:
  - pylint oblivious
  - nosetests
