notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
  - "3.7"
  - "3.8"
cache: pip
install:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
  - tar xvfz libsodium-1.0.18.tar.gz
  - cd libsodium-1.0.18
  - ./configure
  - make
  - make install
  - cd ..
  - pip install pylint
  - pip install coveralls
  - pip install .
script:
  - pylint oblivious
  - nosetests
after_success:
  - coveralls
