notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
  - "3.7"
  - "3.8"
cache: pip
before_install:
  - sudo apt-get -y install libsodium-dev
install:
  - ldconfig -p | grep libsodium
  - sudo ldconfig
  - pip install pylint
  - pip install coveralls
  - pip install .
script:
  - pylint oblivious
  - nosetests
after_success:
  - coveralls
