notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install python --version=3.8.3
        - cp ./libsodium.dll /c/Python38:/c/Python38/Scripts
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install pylint
        - pip install nose
        - pip install coveralls
        - pip install .
script:
  - nosetests
